// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20250209221603_UpdateTodoItem")]
    partial class UpdateTodoItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("desc_Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("desc_Loc");

                    b.Property<string>("descritivos_Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descritivos_Loc");

                    b.Property<string>("est_Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("est_Loc");

                    b.Property<string>("nome_Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome_Loc");

                    b.Property<string>("ref_Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ref_Loc");

                    b.HasKey("Id");

                    b.ToTable("pontos_turisticos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
